# Generated by Django 6.0.4 on 2026-05-10 12:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BurnoutScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.CharField(choices=[('green', 'Healthy'), ('yellow', 'At Risk'), ('red', 'Burned Out')], default='green', max_length=10)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('exhaustion_avg', models.FloatField(default=0)),
                ('cynicism_avg', models.FloatField(default=0)),
                ('efficacy_avg', models.FloatField(default=0)),
                ('manager_consent', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='burnout_score', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_number', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('ex1', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(6)])),
                ('ex2', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(6)])),
                ('ex3', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(6)])),
                ('cy1', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(6)])),
                ('cy2', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(6)])),
                ('cy3', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(6)])),
                ('ef1', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(6)])),
                ('ef2', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(6)])),
                ('ef3', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(6)])),
                ('tasks_completion_rate', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'week_number', 'year')},
            },
        ),
    ]
