# Generated by Django 6.0.4 on 2026-05-11 00:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial_notification_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('task_overdue', 'Task Overdue'), ('new_task', 'New Task'), ('level_up', 'Level Up'), ('badge_earned', 'Badge Earned'), ('milestone_reward', 'Milestone Reward'), ('burnout_change', 'Burnout Change'), ('burnout_alert', 'Burnout Alert'), ('assessment_due', 'Assessment Due'), ('achievement', 'Achievement'), ('reward', 'Reward'), ('streak_update', 'Streak Update'), ('system', 'System')], max_length=50)),
                ('title_template', models.CharField(help_text="Use {variable} placeholders, e.g. 'New task: {task_title}'", max_length=255)),
                ('body_template', models.TextField(help_text='Use {variable} placeholders for the notification body.')),
                ('default_action_url', models.CharField(blank=True, help_text='Optional URL pattern with {variable} placeholders.', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('task_overdue', 'Task Overdue'), ('new_task', 'New Task'), ('level_up', 'Level Up'), ('badge_earned', 'Badge Earned'), ('milestone_reward', 'Milestone Reward'), ('burnout_change', 'Burnout Change'), ('burnout_alert', 'Burnout Alert'), ('assessment_due', 'Assessment Due'), ('achievement', 'Achievement'), ('reward', 'Reward'), ('streak_update', 'Streak Update'), ('system', 'System')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'),
        ),
    ]
